# Demo CI workflow with TcUnit-Runner
name: TcUnit-Runner
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
 
  tcunit_runner:
 
    # a self hosted runner, i.e. VM with tag 'tcunit'
    runs-on: [ self-hosted, tcunit ]
 
    steps:
 
      - name: Checkout repository
        uses: actions/checkout@v2
